## 00. Pytorch Fundamentals

In [ ]:
# Comes with pytorch already
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch
print(torch.__version__)

2.1.0+cu121


In [ ]:
# What is the GPU?
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Introduction to Tensors

### Creating tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [7,8,9]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0], TENSOR[0][1]

(tensor([[1, 2, 3],
         [3, 4, 5],
         [7, 8, 9]]),
 tensor([3, 4, 5]))

In [ ]:
# A new Tensor
TENSOR2 = torch.tensor([
    [
      [1,2,3],
      [4,5,6],
      [7,8,9],
    ],

    [
      [1,2,3],
      [4,5,6],
      [7,8,9]
    ]


])

In [ ]:
TENSOR2.shape

torch.Size([2, 3, 3])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is by starting with tensors full of random numbers and then adjust those random numbers to better represent the data (weights)

https://pytorch.org/docs/stable/generated/torch.randn.html



In [ ]:
# Create a random tensor of shape (3,4)

random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.7660, 0.3109, 0.2171, 0.3460],
         [0.7035, 0.2403, 0.6424, 0.7356],
         [0.9304, 0.7707, 0.3873, 0.7294]],

        [[0.0816, 0.5521, 0.1688, 0.1855],
         [0.6946, 0.4769, 0.6846, 0.5129],
         [0.2173, 0.9424, 0.9120, 0.3069]]])

In [ ]:
random_tensor.shape

torch.Size([2, 3, 4])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(224, 224, 3) #height, width, colorchannels

random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# Dtype starts at float32
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.range()
one_to_ten = torch.range(0, 10)

<ipython-input-25-166437b4bdb2>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  one_to_ten = torch.range(0, 10)


In [ ]:
one_to_ten2 = torch.arange(0, 11)
one_to_ten2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
one_to_ten3 = torch.arange(0, 102, 2)
one_to_ten3

tensor([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
         28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,  54,
         56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,
         84,  86,  88,  90,  92,  94,  96,  98, 100])

In [ ]:
# Creating tensors like
# Grabbing the shape of a tensor for the shape of the new tensor based on zeros
ten_zeros = torch.zeros_like(one_to_ten2)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatype

In [ ]:
# Float32
# https://pytorch.org/docs/stable/tensors

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is
                               device=None, # 'cpu' by default.
                               #tensor operation must be the same among them
                               requires_grad=False) # track gradients when calculations

float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
# Creating a tensor for a different type than the original one

float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting info from tensors

1. Tensors datatype - 'tensor.dtype'
2. tensors shape - 'tensor.shape'
3. Tensors device - 'tensor.device'

In [ ]:
some_tensor = torch.rand(2,4)
some_tensor

tensor([[0.9798, 0.0902, 0.3577, 0.9619],
        [0.9835, 0.4325, 0.0559, 0.7455]])

In [ ]:
# Find details
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}, Shape: {some_tensor.shape} running on {some_tensor.device}")

tensor([[0.9798, 0.0902, 0.3577, 0.9619],
        [0.9835, 0.4325, 0.0559, 0.7455]])
Datatype of tensor: torch.float32, Shape: torch.Size([2, 4]) running on cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication


In [ ]:
# Create a tensor
# ADDITION
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Create a tensor
# MULTIPLICATION
tensor = torch.tensor([1,2,3])
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Create a tensor
# SUBTRACTION
tensor = torch.tensor([1,2,3])
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Create a tensor
# Pytorch in-built function for multiplication
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

How to multipliy in deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product - multiplying matching numbers)



https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [ ]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor*10}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([10, 20, 30])


In [ ]:
matrix1 = torch.tensor([[1,2,3], [4,5,6]])
matrix1

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
matrix1.shape

torch.Size([2, 3])

In [ ]:
matrix2 = torch.tensor([[7,8], [9,10], [11,12]])
matrix2

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [ ]:
matrix2.shape

torch.Size([3, 2])

In [ ]:
# Matrix multiplication
matrix3 = torch.matmul(matrix1, matrix2)
matrix3

tensor([[ 58,  64],
        [139, 154]])

In [ ]:
matrix3.shape

torch.Size([2, 2])

> Remember inner dimensions from the matrices must match and the resulting matrix will have the outer dimensions from the matrices

**2**x<em>3</em> matrix matmul <em>3</em>x**2** equals a 2x2 matrix

In [ ]:
torch.matmul(torch.rand(3,2) , torch.rand(2,3))

tensor([[0.4043, 0.3830, 0.4140],
        [0.7150, 0.5032, 0.6994],
        [0.9025, 0.8582, 0.9249]])

### One of the most common errors in deep learning (shape error)

http://matrixmultiplication.xyz/

In [ ]:
# Shapes for matrix multiplication

tensor_A = torch.tensor([[1,2], [3,4], [5,6]])
tensor_B = torch.tensor([[7,10], [8,11], [9,12]])

tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensors we can manipulate the shape of one of our tensors with transpose


Transpose switches the axis of a tensor

https://discuss.pytorch.org/t/for-beginners-do-not-use-view-or-reshape-to-swap-dimensions-of-tensors/75524

In [ ]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
# torch.mm is the same as matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
x = torch.arange(0, 100, 10)
x.dtype

torch.int64

#### Min

In [ ]:
# Min
torch.min(x)

tensor(0)

#### Max

In [ ]:
# Max
torch.max(x)

tensor(90)

#### Mean

In [ ]:
# Mean
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
x.type(torch.float32).mean()

tensor(45.)

#### Sum

In [ ]:
x.sum(), torch.sum(x)

(tensor(450), tensor(450))

## Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the index in tensor with the lowest value
x.argmin()

tensor(0)

In [ ]:
x[x.argmin()]

tensor(0)

In [ ]:
# Find the index with the highest value
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing, and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape

* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor

 * Stacking - combining different tensors by placing them on top of each other (vstack) or side by side (hstack)

 * Squeeze - removes all '1' dimensions from a tensor

 * Unsqueeze - add a '1' dimension to a target tensor

 * Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
import torch
x = torch.arange(1., 11., )
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 10)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
# Change the view
z = x.view(1,10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
# Changing z changes x because a view of a tensor shares the same memory as the original input
z[:,0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
# STack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [ ]:
# toch.squeeze() - removes all single dimensions
x_reshaped

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [ ]:
x_reshaped.shape

torch.Size([1, 10])

In [ ]:
x_reshaped.squeeze()

tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([10])

In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

print("Sqeezing...")
x_squeezed = x_reshaped.squeeze()

print(f"New tensor: {x_squeezed}")
print(f"Previous tensor: {x_squeezed.shape}")

Previous tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
Previous shape: torch.Size([1, 10])
Sqeezing...
New tensor: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Previous tensor: torch.Size([10])


In [ ]:
# Torch unsqueeze - adds a single dimension to a target tensor at specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"New Tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Previous shape: torch.Size([10])
New Tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
New shape: torch.Size([1, 10])


In [ ]:
#torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size = (224, 224, 3)) #[height, width, colour_channels]

# Permute the original tensor to rearrange the axis
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0 to 1, 1 to 2, and 2 to 0
x_permuted.shape

torch.Size([3, 224, 224])

In [ ]:
x_original[0,0,0] = 728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

### Indexing (selecting data from tensors)

Indexing with PyTorch is similar to Numpy


In [ ]:
# Create a tensor

import torch
x = torch.arange(1,10).reshape(1,3,3) # HAs to be compatible with the original shape
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# let´s index on the new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Index on the middle bracket
x[0][0], x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
# Index on the most inner bracket
x[0][0][0]

tensor(1)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
# You can use ":" to select "all" from a target dimension
x[:, 0] # all from the 0 dimension from the element

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimension but only index 1 of 2dn dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0th dimension but only the 1 index value of the first and second dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and first dimension and all values of the second dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 9
x[:, 2, 2]

tensor([9])

In [ ]:
# Index on x to return 3,6,9
x[:, :, 2]

tensor([[3, 6, 9]])

## Pytorch tensors and numpy

Numpy is a popular scientific Python numerical computing library.

Pytorch has functionality to interact with it

* Data in Numpy arrays, want in Pytorch tensors -> `torch.from_numpy(ndarray)`

* Pytorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [ ]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # use .type(torch.float32) since default convertion type from numpy is float64
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
tensor.dtype # Since this was converted from np array

torch.float64

In [ ]:
torch.arange(1.0, 8.0).dtype # torch default dtype

torch.float32

In [ ]:
# Change the value of the array
# What will happen to tensor?

array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to np array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

In [ ]:
# Change the tensor, what happens to numpy tensor?
tensor = tensor + 1
numpy_tensor, tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([2., 2., 2., 2., 2., 2., 2.]))

## Reproducability (trying to take the randomness out of random)


In short, how a neural network learns:

`start with random numbers, tensor operations, update random numbers, again, again, again, ....`

To reduce randomness in NN and pytorch comes the concept of a random seed. Essentially, what the random seed does is 'flavour' the randomness.


In [ ]:
import torch

# Create random tensor
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_B == random_tensor_A)

tensor([[0.1043, 0.8554, 0.1448, 0.0227],
        [0.1277, 0.2625, 0.6996, 0.1436],
        [0.7958, 0.8244, 0.0861, 0.3498]])
tensor([[0.8326, 0.1395, 0.0676, 0.7853],
        [0.9321, 0.4377, 0.3629, 0.5826],
        [0.7854, 0.7930, 0.6063, 0.5096]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# let´s make some random but reproducible tensors
import torch

# Set random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and Pytorch objects on the GPUs (and making faster computations)

GPUs = computations on numbers, thanks to CUDA + NVIDA hardware + Pytorch working behind the scenes

### Getting a GPU

1. Easiest - Use google colab (options pro here)
2. Use your own GPU - takes a little bit of setup and investment (lots of options)
3. Use cloud computing _ GCP, AWS, Azure, these services allow you to rent computers on the cloud

For 2, 3 Pytorch + GPU drivers (CUDA) takes a time of setting up, to do this, refer to Pytorch setup documentation



### Check for GPU access with Pytorch

In [1]:
!nvidia-smi

Sat Mar  2 18:08:56 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For Pytorch since it´s capabale of running in both GPU or CPU, it´s best practice to setup device agnostic code

In [3]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
# Count the number of GPUs
torch.cuda.device_count()

1

## 3. Putting tensors and models on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [5]:
# Create a tensor (default on CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [6]:
# Move tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [7]:
# Move tensor to CPU, since if the tensor is in the GPU you can´t transform it with Numpy
tensor_on_cpu = tensor_on_gpu.cpu()

In [9]:
tensor_on_cpu.device, tensor_on_cpu

(device(type='cpu'), tensor([1, 2, 3]))

In [10]:
tensor_on_cpu.numpy()

array([1, 2, 3])

## Exercises

In [11]:
import torch

In [22]:
# Create a random tensor with shape (7, 7)
random_tensor = torch.rand(7,7)
random_tensor

tensor([[0.2770, 0.6753, 0.7346, 0.1358, 0.5691, 0.9267, 0.5312],
        [0.0693, 0.5334, 0.5095, 0.3455, 0.1664, 0.1234, 0.9705],
        [0.2514, 0.9813, 0.7789, 0.7307, 0.1700, 0.4335, 0.1881],
        [0.6216, 0.1464, 0.9095, 0.0774, 0.8926, 0.7138, 0.4027],
        [0.3876, 0.4263, 0.6787, 0.0490, 0.4919, 0.7757, 0.1115],
        [0.4999, 0.3528, 0.5085, 0.5425, 0.0760, 0.7619, 0.5812],
        [0.2798, 0.9438, 0.3615, 0.9269, 0.0296, 0.8110, 0.9128]])

Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [24]:
random_tensor_2 = torch.rand(1,7)
random_tensor_2.shape, random_tensor_2.T.shape

(torch.Size([1, 7]), torch.Size([7, 1]))

In [27]:
random_matrix = torch.matmul(random_tensor, random_tensor_2.T)
random_matrix.shape

torch.Size([7, 1])

Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234

In [32]:
RANDOM_SEED = 1234
torch.cuda.manual_seed(RANDOM_SEED)

In [33]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [35]:
new_matrix = torch.matmul(tensor_A, tensor_B.T)
new_matrix.shape

torch.Size([2, 2])

In [39]:
max = torch.max(new_matrix)
max

tensor(0.5617, device='cuda:0')

In [40]:
min = torch.min(new_matrix)
min

tensor(0.3647, device='cuda:0')